logging.level.org.springframework.boot.autoconfigure: ERROR
server:
  port: 6869
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=UTC
    username: root
    password: 932492swb
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    connectionProperties: druid.stat.mergeSql=true
mybatis:
  type-aliases-package: com.swb.ssm.service.entity
  mapper-locations: classpath:mybatis/mapper/*.xml